name: Close issues
on:
  issues:
    types:
      - closed
jobs:
  close_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --remove-label "$REMOVE_LABELS"
      - run: gh issue edit "$NUMBER" --add-label "$ADD_LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          REMOVE_LABELS: active 
          Add_LABELS: done
