name: Move new issues into In Progress

on:
  issues:
    types: [assigned]

permissions:
  issues: write

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Library Management System
          column: In progress
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
